-- ============================================================
-- AI CAREER MENTOR - MYSQL SCHEMA
-- Applied automatically by app/services/db.py on startup
-- (CREATE TABLE IF NOT EXISTS, so this is safe to re-run).
-- ============================================================

CREATE TABLE IF NOT EXISTS students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    -- nullable in the DB (existing rows predate these columns) but required
    -- by the /auth/signup contract; identity and login are enforced there,
    -- not by DB constraints, so existing dev databases don't need to be dropped
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    interests JSON NOT NULL,
    hobbies JSON NOT NULL,
    riasec_answers JSON,
    riasec_scores JSON NOT NULL,
    academics JSON NOT NULL,
    self_rated_skills JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Careers are denormalized (courses/colleges/scholarships/certifications as
-- JSON) per docs/02b_DATA_MODEL.md's "Notes on scale" — the dataset is curated
-- and small (~30 rows), so this avoids five extra join tables for no benefit.
-- careers_seed.json is the source of truth for this table, which is
-- auto-seeded from it on first startup (see db.py:init_db).
CREATE TABLE IF NOT EXISTS careers (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    riasec_tags JSON NOT NULL,
    relevant_subjects JSON NOT NULL,
    required_skills JSON NOT NULL,
    interest_tags JSON NOT NULL,
    courses JSON NOT NULL,
    colleges JSON NOT NULL,
    scholarships JSON NOT NULL,
    certifications JSON NOT NULL,
    emerging BOOLEAN NOT NULL DEFAULT FALSE
);

-- Full mentor conversation history, so /mentor/chat can show prior turns
-- instead of answering each message with no memory of the conversation.
CREATE TABLE IF NOT EXISTS mentor_chat (
    message_id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    sender ENUM('student', 'ai') NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

-- Roadmap steps generated by /score/insights, so a student can track
-- progress (checked off) across visits instead of the roadmap being
-- regenerated as disposable text every time.
CREATE TABLE IF NOT EXISTS roadmap_steps (
    step_id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    career VARCHAR(150) NOT NULL,
    step_number INT NOT NULL,
    description TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

-- Last generated AI insights per student, so the Dashboard can show them
-- again without re-hitting the LLM every time the page reloads. One row
-- per student — regenerating (POST /score/insights) overwrites it.
CREATE TABLE IF NOT EXISTS insights (
    student_id INT PRIMARY KEY,
    top_career VARCHAR(150) NOT NULL,
    explanations JSON NOT NULL,
    emerging_trend TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

